esphome:
  name: ${devicename}

esp32:
  board: esp32-evb

# Enable logging
logger:
  level: ${log_level}

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 0

# I2C Bus
i2c:
  sda: GPIO13
  scl: GPIO16
  scan: true
  id: bus_a  